### ISSUE TITLE
There should be no need to add an IP when it is configured as Local Push

### ISSUE THREAD

**Issue by edurenye** [luuuis/hass_wibeee#98]
Now when you need to add a new Wibeee device you always have to set the IP Address if the device, but there should be no need for it if you are setting in up as Local Push instead of using pull.

So as a first step in configuration you should be able to select the optional 'Local Push' option and then there should be no need to add any IP Address.

**Comment by luuuis** [comment]
Hi @edurenye,

Interesting idea. In theory it is possible to auto-detect the device like that but it would be a lot of rework for little benefit IMO.

What are you trying to achieve, actually? Do you add many devices or is it a case of changing IP addresses?

**Comment by edurenye** [comment]
Hi @luuuis,
My Wibeee is configured to send data to my HA, but when I try to add the device to HA, I think that pull is too much for the Wibeee, and it shuts down and resets, so I need to configure it again from my phone.

I'm starting to think about replacing the Wibeee for another device.

And this happened because I replaced the router, so the new router gave the Wibeee another IP, I removed it from HA to re-add it, but I could not manage to configure it again.

**Comment by edurenye** [comment]
My Wibeee was never configured to use Wibeee Nest cloud, that device used the SolarProfit servers by default, and every time I reset it goes back to those servers.

But last year that company went bankrupt, and now their servers no longer work.

My device has a modified firmware I guess, maybe I should install an official Wibeee firmware, but I do not know how to do it.

**Comment by luuuis** [comment]
I see. What have you configured in hass_wibeee for Local Push?

Regardless, please follow the steps and see if that works to add your device.

**Comment by edurenye** [comment]
I still have added the old nonworking servers of SolarProfit.
I'll try, and I'll tell you how it went.

Thanks for your help!

**Comment by edurenye** [comment]
I tried to reset the device, configure it with the Nest app and seems to work, kind of, I found this error "Invalid flow specified" when I was configuring it, but the device was added and showed the right numbers, it still gets 0 in all values from time to time, but most of the time works.

To solve that, I tried to configure it to push instead of polling. But I got again "Invalid flow specified" while I was configuring it. The config gets saved, but shows the error in the UI.

I added the debug option to see the error in the logs, but after that the changes in the config were not giving errors anymore.

Now seems to be working, and no more resets, at least for now. But I get some strange numbers from the device, like WIBEEE Active Energy L4 -> 9.223.372.036.854.776.000 Wh which is really weird, but WIBEEE Active Power L4 -> 484 W.
That seems to be a problem with the device, not with this integration. And I use the Active Power with https://github.com/flixlix/power-flow-card-plus because the official HA widgets just let me use the Energy sensors.

**Comment by edurenye** [comment]
There are still things I do not understand, my device has phase1, phase2 and phase3, but in HA, it has L1, L2, L3 and L4. What is the extra one?

Also in the Box phase1 gives me this data:
```
AT+CIPSENDBUF=4,316
135
{"time":"1735730966","v1":"233.97","v2":"233.97","v3":"233.97","vt":"233.00","i1":"2.73","i2":"1.71","i3":"0.00","it":"4.44","p1":"638","p2":"400","p3":"0","pt":"1037","pm1":"646","pm2":"406","pm3":"0","pmt":"1
```

While in HA in L1 I get:
WIBEEE Active Energy L1: 9.223.372.036.854.776.000 Wh
WIBEEE Active Power L1: 314 W
WIBEEE Apparent Power L1: 494 VA
WIBEEE Capacitive Reactive Energy L1: 9.223.372.036.854.776.000 varh
WIBEEE Current L1: 2,04 A
WIBEEE Frequency L1: 50,30 Hz
WIBEEE Phase Voltage L1: 235,68 V
WIBEEE Power Factor L1: 0,658
WIBEEE Reactive Power L1: -361 var

I do not understand from where those big numbers come from.

**Comment by edurenye** [comment]
Oh, I see that it gets the data from `/en/status.xml` not from `/en/phase1.html`.

There I can see the big numbers, but why they are so big?

```
<response>
<model>WBB</model>
<webversion>4.4.157</webversion>
<time>1742257567</time>
<fase1_vrms>236.53</fase1_vrms>
<fase1_irms>2.06</fase1_irms>
<fase1_p_aparent>488.00</fase1_p_aparent>
<fase1_p_activa>314.40</fase1_p_activa>
<fase1_p_reactiva_ind>0.00</fase1_p_reactiva_ind>
<fase1_p_reactiva_cap>373.22</fase1_p_reactiva_cap>
<fase1_frecuencia>50.15</fase1_frecuencia>
<fase1_factor_potencia>0.644</fase1_factor_potencia>
<fase1_energia_activa>9223372036854775808</fase1_energia_activa>
<fase1_energia_reactiva_ind>9223372036854775808</fase1_energia_reactiva_ind>
<fase1_energia_reactiva_cap>9223372036854775808</fase1_energia_reactiva_cap>
<fase1_angle>0.00</fase1_angle>
<fase1_thd_total>42.40</fase1_thd_total>
<fase1_thd_fund>1.90</fase1_thd_fund>
<fase1_thd_ar3>0.40</fase1_thd_ar3>
<fase1_thd_ar5>0.60</fase1_thd_ar5>
<fase1_thd_ar7>0.30</fase1_thd_ar7>
<fase1_thd_ar9>0.30</fase1_thd_ar9>
<fase1_thd_tot_V>3.10</fase1_thd_tot_V>
<fase1_thd_fun_V>236.50</fase1_thd_fun_V>
<fase1_thd_ar3_V>0.00</fase1_thd_ar3_V>
<fase1_thd_ar5_V>7.40</fase1_thd_ar5_V>
<fase1_thd_ar7_V>0.00</fase1_thd_ar7_V>
<fase1_thd_ar9_V>0.00</fase1_thd_ar9_V>
<fase2_vrms>236.53</fase2_vrms>
<fase2_irms>0.21</fase2_irms>
<fase2_p_aparent>49.24</fase2_p_aparent>
<fase2_p_activa>0.00</fase2_p_activa>
<fase2_p_reactiva_ind>0.00</fase2_p_reactiva_ind>
<fase2_p_reactiva_cap>0.00</fase2_p_reactiva_cap>
<fase2_frecuencia>50.15</fase2_frecuencia>
<fase2_factor_potencia>0.000</fase2_factor_potencia>
<fase2_energia_activa>9223372036854775808</fase2_energia_activa>
<fase2_energia_reactiva_ind>9223372036854775808</fase2_energia_reactiva_ind>
<fase2_energia_reactiva_cap>9223372036854775808</fase2_energia_reactiva_cap>
<fase2_angle>0.00</fase2_angle>
<fase2_thd_total>0.00</fase2_thd_total>
<fase2_thd_fund>0.00</fase2_thd_fund>
<fase2_thd_ar3>0.00</fase2_thd_ar3>
<fase2_thd_ar5>0.00</fase2_thd_ar5>
<fase2_thd_ar7>0.00</fase2_thd_ar7>
<fase2_thd_ar9>0.00</fase2_thd_ar9>
<fase2_thd_tot_V>3.10</fase2_thd_tot_V>
<fase2_thd_fun_V>236.50</fase2_thd_fun_V>
<fase2_thd_ar3_V>0.00</fase2_thd_ar3_V>
<fase2_thd_ar5_V>7.40</fase2_thd_ar5_V>
<fase2_thd_ar7_V>0.00</fase2_thd_ar7_V>
<fase2_thd_ar9_V>0.00</fase2_thd_ar9_V>
<fase3_vrms>236.53</fase3_vrms>
<fase3_irms>0.00</fase3_irms>
<fase3_p_aparent>0.00</fase3_p_aparent>
<fase3_p_activa>0.00</fase3_p_activa>
<fase3_p_reactiva_ind>0.00</fase3_p_reactiva_ind>
<fase3_p_reactiva_cap>0.00</fase3_p_reactiva_cap>
<fase3_frecuencia>50.15</fase3_frecuencia>
<fase3_factor_potencia>0.000</fase3_factor_potencia>
<fase3_energia_activa>9223372036854775808</fase3_energia_activa>
<fase3_energia_reactiva_ind>9223372036854775808</fase3_energia_reactiva_ind>
<fase3_energia_reactiva_cap>9223372036854775808</fase3_energia_reactiva_cap>
<fase3_angle>0.00</fase3_angle>
<fase3_thd_total>0.00</fase3_thd_total>
<fase3_thd_fund>0.00</fase3_thd_fund>
<fase3_thd_ar3>0.00</fase3_thd_ar3>
<fase3_thd_ar5>0.00</fase3_thd_ar5>
<fase3_thd_ar7>0.00</fase3_thd_ar7>
<fase3_thd_ar9>0.00</fase3_thd_ar9>
<fase3_thd_tot_V>3.10</fase3_thd_tot_V>
<fase3_thd_fun_V>236.50</fase3_thd_fun_V>
<fase3_thd_ar3_V>0.00</fase3_thd_ar3_V>
<fase3_thd_ar5_V>7.40</fase3_thd_ar5_V>
<fase3_thd_ar7_V>0.00</fase3_thd_ar7_V>
<fase3_thd_ar9_V>0.00</fase3_thd_ar9_V>
<fase4_vrms>236.53</fase4_vrms>
<fase4_irms>2.27</fase4_irms>
<fase4_p_aparent>537.24</fase4_p_aparent>
<fase4_p_activa>314.40</fase4_p_activa>
<fase4_p_reactiva_ind>0.00</fase4_p_reactiva_ind>
<fase4_p_reactiva_cap>373.22</fase4_p_reactiva_cap>
<fase4_frecuencia>50.15</fase4_frecuencia>
<fase4_factor_potencia>0.585</fase4_factor_potencia>
<fase4_energia_activa>9223372036854775808</fase4_energia_activa>
<fase4_energia_reactiva_ind>9223372036854775808</fase4_energia_reactiva_ind>
<fase4_energia_reactiva_cap>9223372036854775808</fase4_energia_reactiva_cap>
<scale>60</scale>
<coilStatus>-</coilStatus>
<ground>0.00</ground>
</response>
```

I see in this comment similar values:
https://github.com/luuuis/hass_wibeee/issues/69#issuecomment-1938615630

I do not understand, I'm not using 9.223.372.036.854.776.000 Wh.

**Comment by luuuis** [comment]
1. @edurenye we do not use `status.xml` anymore, we use only the official `values.xml` API.
2. The _L4 sensors are the totals on three-phase devices, it's described in https://github.com/luuuis/hass_wibeee?tab=readme-ov-file#sensors.
3. Regarding the energy counters, you can reset them in the UI of the device under **Metrology → Configuration → Energy Counter → Reset**.

**Comment by edurenye** [comment]
Ah ok, thanks for your help. Would be great, a way to debug all the queries done to values.xml.

Resetting the counters has fixed the weird values.

The problem I see is that my installation just uses L1 for both the grid input and output (both with the same sign) and L2 for the solar input. Which makes it hard to know how much energy is really coming in or out. I guess I'll need to use some helper to adapt the values and pass them to the Home Assistant energy panel.

**Comment by luuuis** [comment]
Have a read through the [sensor examples in the Wiki](https://github.com/luuuis/hass_wibeee/wiki/Sensor-Examples) as that is covered there.

I will clean this issue up a bit since the latest comments are no longer related to how the integration is configured (IP address).

**Comment by luuuis** [comment]
@edurenye I have released [v4.0.0](https://github.com/luuuis/hass_wibeee/releases/tag/v4.0.0), which allows to use Wibeee with polling completely disabled (the new default). In my local testing this has finally made the device stable in HA.

Please try the release, I am interested in your experience with the new approach.

**Comment by edurenye** [comment]
Thanks for all the efforts and work @luuuis 

It's nice to have the new notifications, so now I know when it is working and when not. So far in 3 days I just have received one notification. And it has been down for a small amount of time. It works better than before, but still not perfect. But maybe now it's just that the device is not powerful enough, I don't know how it works without home assistant, just with the Wibeee servers to compare.

```Wibeee D7B747 has not received an update since Mon Mar 31 12:39:19 2025. Configure Local Push to get updates when sensor values change.```

**Comment by edurenye** [comment]
Mine does not have as many options:

![Image](https://github.com/user-attachments/assets/7149815d-19d3-43ae-99da-af97efc92f1d)

But data refresh time is also set to 1 min, that was the default value.

**Comment by luuuis** [comment]
> It's nice to have the new notifications, so now I know when it is working and when not. So far in 3 days I just have received one notification. And it has been down for a small amount of time.

The notification are still under development, in the version you have they can show problems when everything is ok. Feel free to ignore for now.

**Comment by luuuis** [comment]
Ok so with (v4.1.0-beta)[https://github.com/luuuis/hass_wibeee/releases/tag/v4.1.0-beta] we now expose diagnostic sensors with the current IP. That means that if your Wibeee device changes IP but continues to send push data to Home Assistant, the new IP will be available in HA and the sensors will update correctly (sensor updates are based on the MAC address, which doesn't change).
 
There is no polling anymore so it will not happen that the device goes unavailable for trying to poll the old IP. The only limitation that remains that the VISIT link of the device may still point to the old IP address after this happens. I will fix this in a subsequent release, in any case it doesn't seem too serious as you have the new IP available in the sensors.

<img width="670" alt="Image" src="https://github.com/user-attachments/assets/3cb7afff-6b3b-45b0-8f92-69e80fb52def" />

**Comment by edurenye** [comment]
The repairs were right, because I checked the history, and the data was not updated from the time of the repair onwards. Also, I no longer have the problem with the changing IPs since I added a router that allows me to control the DHCP server. But this will help me simplify my network a bit now.

I'll try the new beta, see how it goes. Thank you!

**Comment by edurenye** [comment]
I tried the beta, the 'Visit' link works, but I do not have the 'Diagnostic' box.
Anyway, from outside the network I can't check directly the 'Visit' link, but I'm tunneling the connection through ssh to check if the IP works or not.

**Comment by luuuis** [comment]
[v4.1.0](https://github.com/luuuis/hass_wibeee/releases/tag/v4.1.0) no longer supports polling and will update the IP address in HA if it changes.

IP address is required only when initially adding the device (needed to discover the supported sensors).
